# Generated by Django 5.0.7 on 2024-08-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
