# Generated by Django 5.0.7 on 2024-08-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('birthday_date', models.DateField()),
                ('user_profile', models.ForeignKey(limit_choices_to={'user_type': 'company'}, on_delete=django.db.models.deletion.CASCADE, to='secman.userprofile')),
            ],
        ),
    ]
