# Generated by Django 5.0.7 on 2024-08-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secman', '0002_birthdaycompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetails',
            name='partialuniform',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarydetails',
            name='price_partial_uniform',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
