# Generated by Django 5.0.7 on 2024-08-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secman', '0003_salarydetails_partialuniform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydetails',
            name='partialuniform',
        ),
        migrations.AddField(
            model_name='employeejoining',
            name='partialuniform',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
