# Generated by Django 5.0.7 on 2024-08-13 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secman', '0004_employeejoining_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejoining',
            name='company',
            field=models.ForeignKey(limit_choices_to={'user_type': 'company'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='secman.userprofile'),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='emergency_contact1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='emergency_contact2',
            field=models.CharField(max_length=15),
        ),
    ]
