# Generated by Django 5.0.7 on 2024-08-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secman', '0005_salarydetails_advance_payment_approval_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeejoining',
            old_name='emergency_contact_relation1_address',
            new_name='emergency_contact_relation1_name',
        ),
        migrations.RenameField(
            model_name='employeejoining',
            old_name='emergency_contact_relation2_address',
            new_name='emergency_contact_relation2_name',
        ),
        migrations.RemoveField(
            model_name='employeejoining',
            name='partialuniform',
        ),
        migrations.DeleteModel(
            name='AdvancePayment',
        ),
    ]
