# Generated by Django 5.0.7 on 2024-08-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secman', '0006_rename_emergency_contact_relation1_address_employeejoining_emergency_contact_relation1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarydetails',
            name='advance_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
