# Generated by Django 5.0.7 on 2024-08-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secman', '0006_employeejoining_basic_salary_employeejoining_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejoining',
            name='basic_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='bonus',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='conveyance_allowance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='education_allowance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='esic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='gratuity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='hours_daily_duty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='hra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='leave_with_wages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='paid_holiday',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='pf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='service_charge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='special_allowance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='total_b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='total_c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='travelling_allowance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeejoining',
            name='uniform',
            field=models.IntegerField(),
        ),
    ]
