# Generated by Django 5.0.7 on 2024-08-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secman', '0010_shifttime_alter_attendance_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttime',
            name='shift_total_time',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
