# Generated by Django 5.0.7 on 2024-08-19 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secman', '0011_shifttime_shift_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejoining',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secman.shifttime'),
        ),
    ]
