# Generated by Django 5.0.7 on 2024-08-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetails',
            name='actual_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
